<?php

/**
 * @var string $vendorDir
 * @var string $version
 */

return <<<TEMPLATE
<?php

/**
 * Plugin Name: Composer autoload
 * Description: Auto-generated by https://github.com/wp-plus/composer-autoload. Loads Composer's `autoload.php`.
 * Version: $version
 * Author: WP+
 * Author URI: https://github.com/wp-plus
 */

require '$vendorDir/autoload.php';

TEMPLATE;
